set_property IOSTANDARD LVCMOS33 [get_ports {col[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {col[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {col[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {col[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {keyboard_val[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {keyboard_val[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {keyboard_val[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {keyboard_val[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {keyboard_val[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {keyboard_val[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {keyboard_val[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {row[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {row[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {row[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {row[0]}]
set_property PACKAGE_PIN L5 [get_ports {col[0]}]
set_property PACKAGE_PIN J6 [get_ports {col[1]}]
set_property PACKAGE_PIN K6 [get_ports {col[2]}]
set_property PACKAGE_PIN M2 [get_ports {col[3]}]
set_property PACKAGE_PIN K3 [get_ports {row[0]}]
set_property PACKAGE_PIN L3 [get_ports {row[1]}]
set_property PACKAGE_PIN J4 [get_ports {row[2]}]
set_property PACKAGE_PIN K4 [get_ports {row[3]}]
set_property PACKAGE_PIN Y18 [get_ports i_clk]
set_property PACKAGE_PIN W4 [get_ports i_rst_n]
set_property PACKAGE_PIN F16 [get_ports {keyboard_val[3]}]
set_property PACKAGE_PIN E17 [get_ports {keyboard_val[2]}]
set_property PACKAGE_PIN C15 [get_ports {keyboard_val[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports i_clk]
set_property IOSTANDARD LVCMOS33 [get_ports i_rst_n]

set_property PACKAGE_PIN C14 [get_ports {keyboard_val[1]}]
set_property PACKAGE_PIN F13 [get_ports {keyboard_val[5]}]
set_property PACKAGE_PIN F14 [get_ports {keyboard_val[4]}]
set_property PACKAGE_PIN F15 [get_ports {keyboard_val[6]}]

set_property IOSTANDARD LVCMOS33 [get_ports {buzzer_out[0]}]
set_property PACKAGE_PIN R4 [get_ports buzzer_in]
set_property IOSTANDARD LVCMOS33 [get_ports buzzer_in]

set_property IOSTANDARD LVCMOS33 [get_ports {buzzer_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {buzzer_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports buzzer_in0]
set_property IOSTANDARD LVCMOS33 [get_ports buzzer_in1]
set_property IOSTANDARD LVCMOS33 [get_ports buzzer_in2]
set_property PACKAGE_PIN Y9 [get_ports buzzer_in0]
set_property PACKAGE_PIN W9 [get_ports buzzer_in1]
set_property PACKAGE_PIN Y7 [get_ports buzzer_in2]
set_property PACKAGE_PIN A19 [get_ports {buzzer_out[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports buzzer_out]
set_property PACKAGE_PIN A19 [get_ports buzzer_out]


set_property IOSTANDARD LVCMOS33 [get_ports buzzer_in3]
set_property IOSTANDARD LVCMOS33 [get_ports buzzer_in4]
set_property IOSTANDARD LVCMOS33 [get_ports buzzer_in5]
set_property IOSTANDARD LVCMOS33 [get_ports buzzer_in6]
set_property IOSTANDARD LVCMOS33 [get_ports buzzer_in7]
set_property PACKAGE_PIN Y8 [get_ports buzzer_in3]
set_property PACKAGE_PIN AB8 [get_ports buzzer_in4]
set_property PACKAGE_PIN AA8 [get_ports buzzer_in5]
set_property PACKAGE_PIN V8 [get_ports buzzer_in6]
set_property PACKAGE_PIN V9 [get_ports buzzer_in7]
